namespace Google.GenerativeAI.Gemini
{
    using System.Runtime.Serialization;

    /// <summary>
    /// Specifies the originator of the content in a Gemini API request or response.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The <c>role</c> field is crucial for maintaining context in a multi-turn conversation.
    /// </para>
    /// <list type="bullet">
    ///   <item>
    ///     <term>User</term>
    ///     <description>Content from the end-user interacting with the model.</description>
    ///   </item>
    ///   <item>
    ///     <term>Model</term>
    ///     <description>Response previously generated by the AI model.</description>
    ///   </item>
    ///   <item>
    ///     <term>Function</term>
    ///     <description>Result of a function call, provided back to the model.</description>
    ///   </item>
    ///   <item>
    ///     <term>Tool</term>
    ///     <description>Output of a tool execution, provided to the model.</description>
    ///   </item>
    /// </list>
    /// </remarks>
    public enum ContentRole
    {
        /// <summary>
        /// Indicates that the content is from the end-user who is interacting with the model.
        /// </summary>
        [EnumMember(Value = "user")]
        User,

        /// <summary>
        /// Represents a response that was previously generated by the AI model.
        /// </summary>
        [EnumMember(Value = "model")]
        Model,

        /// <summary>
        /// Used to provide the result of a function call back to the model.
        /// </summary>
        [EnumMember(Value = "function")]
        Function,

        /// <summary>
        /// Used when providing the model with the output of a tool execution.
        /// </summary>
        [EnumMember(Value = "tool")]
        Tool
    }
}