namespace Google.GenerativeAI.Gemini.Textual.Request

{
    using System.Text.Json.Serialization;

    /// <summary>
    /// A union type representing a single piece of data in a content block.
    /// </summary>
    public class Part
    {
        /// <summary>
        /// Inline text.
        /// </summary>
        [JsonPropertyName("text")]
        public string? Text { get; set; }

        /// <summary>
        /// Inline media data (e.g., image, audio, video).
        /// </summary>
        [JsonPropertyName("inlineData")]
        public Blob? InlineData { get; set; }

        /// <summary>
        /// A predicted function call generated by the model.
        /// </summary>
        [JsonPropertyName("functionCall")]
        public FunctionCall? FunctionCall { get; set; }

        /// <summary>
        /// The response to a function call.
        /// </summary>
        [JsonPropertyName("functionResponse")]
        public FunctionResponse? FunctionResponse { get; set; }
    }
}