/// <summary>
/// Represents the full response payload from the Gemini API.
/// </summary>
namespace Google.GenerativeAI.Gemini.Textual.Response

{
    using Google.GenerativeAI.Gemini.Textual.Request;
    using System.Text.Json.Serialization;

    /// <summary>
    /// A single candidate response generated by the model.
    /// </summary>
    public class Candidate
    {
        /// <summary>
        /// The content of the generated response.
        /// </summary>
        [JsonPropertyName("content")]
        public Content Content { get; set; }

        /// <summary>
        /// The reason the model stopped generating tokens (e.g., "STOP", "MAX_TOKENS", "SAFETY").
        /// </summary>
        [JsonPropertyName("finishReason")]
        public string? FinishReason { get; set; }

        /// <summary>
        /// The index of this candidate in the list of candidates.
        /// </summary>
        [JsonPropertyName("index")]
        public int Index { get; set; }

        /// <summary>
        /// A list of safety ratings for this specific candidate response.
        /// </summary>
        [JsonPropertyName("safetyRatings")]
        public List<SafetyRating> SafetyRatings { get; set; }

        /// <summary>
        /// Citation metadata for the generated content.
        /// </summary>
        [JsonPropertyName("citationMetadata")]
        public CitationMetadata? CitationMetadata { get; set; }
    }
}