/// <summary>
/// Represents the full response payload from the Gemini API.
/// </summary>
namespace Google.GenerativeAI.Gemini.Textual.Response

{
    using System.Text.Json.Serialization;

    public class GeminiResponse
    {
        /// <summary>
        /// A list of candidate responses generated by the model.
        /// </summary>
        [JsonPropertyName("candidates")]
        public List<Candidate> Candidates { get; set; }

        /// <summary>
        /// Information about the prompt's safety feedback. If the prompt was blocked,
        /// this field will contain the reason.
        /// </summary>
        [JsonPropertyName("promptFeedback")]
        public PromptFeedback? PromptFeedback { get; set; }

        /// <summary>
        /// Metadata on the token usage of the request.
        /// </summary>
        [JsonPropertyName("usageMetadata")]
        public UsageMetadata? UsageMetadata { get; set; }
    }
}